cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart_page'),
    path('update-item/', views.update_item, name='update_item'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('report-order/', views.OrderReportAnonymous.as_view(), name='report_order_anony'),
    path('order-detail/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/password/change/', views.CustomPasswordChangeView.as_view(), name='custom_account_change_password'),
    path('accounts/password/set/', views.CustomPasswordSetView.as_view(), name='custom_account_set_password'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('general.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, re_path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='products_list'),
    path('search/', views.SearchView.as_view(), name='search_page'),
    path('favorite/', views.favorite_view, name='favorite'),
    re_path(r'category/(?P<slug>[-\w]+)/', views.CategoryView.as_view(), name='category_page'),
    re_path(r'(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name='product_detail'),
]

cart/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _

from products.models import Product


class Order(models.Model):
    customer = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='order', null=True,
                                 blank=True, verbose_name=_('customer'))
    first_name = models.CharField(max_length=200, null=True, verbose_name=_('first name'))
    last_name = models.CharField(max_length=200, null=True, verbose_name=_('last name'))
    email = models.EmailField(max_length=254, null=True, verbose_name=_('email'))
    phone = PhoneNumberField(null=True, region='IR', verbose_name=_('phone'))
    order_note = models.TextField(null=True, blank=True, verbose_name=_('order note'))
    completed = models.BooleanField(default=False, blank=True, verbose_name=_('completed'))
    transaction = models.CharField(max_length=200, null=True, verbose_name=_('transaction'))

    datetime_ordered = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime ordered'))
    datetime_payed = models.DateTimeField(null=True, verbose_name=_('datetime payed'))

    # backup
    get_cart_total_no_discount_past = models.PositiveIntegerField(null=True,
                                                                  verbose_name=_('get cart total no discount'))
    get_cart_total_discount_past = models.PositiveIntegerField(null=True,
                                                               verbose_name=_('get cart total discount'))
    get_cart_total_profit_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total profit'))
    get_cart_total_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total'))
    get_cart_items_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total'))

    def __str__(self):
        return str(self.id)

    def act_items(self):
        return self.items.filter(product__active=True)

    def del_in_act_items(self):
        return self.items.filter(product__active=False).delete()

    def backup_total(self):
        self.get_cart_total_no_discount_past = self.get_cart_total_no_discount
        self.get_cart_total_discount_past = self.get_cart_total_discount
        self.get_cart_total_profit_past = self.get_cart_total_profit
        self.get_cart_total_past = self.get_cart_total
        self.get_cart_items_past = self.get_cart_items
        self.save()

    @property
    def get_cart_items(self):
        return sum([item.quantity for item in self.act_items()])

    @property
    def get_cart_total_no_discount(self):
        return sum([item.get_total_no_discount for item in self.act_items()])

    @property
    def get_cart_total_discount(self):
        return sum([item.get_total_discount for item in self.act_items()])

    @property
    def get_cart_total_profit(self):
        return sum([item.get_total_profit for item in self.act_items()])

    @property
    def get_cart_total(self):
        return self.get_cart_total_no_discount - self.get_cart_total_profit

    @property
    def shipping(self):
        shipping = False
        for i in self.act_items():
            if not i.product.digital:
                shipping = True
        return shipping

    def format_time_ordered(self):
        return self.datetime_ordered.strftime('%B %d, %Y')

    def format_time_payed(self):
        return self.datetime_payed.strftime('%B %d, %Y')

    @property
    def avg_track_items(self):
        try:
            avg = sum([item.track_order for item in self.items.all()]) / len(self.items.all())
        except ZeroDivisionError:
            return 'zero'
        if 0 <= avg <= 20:
            return _('Paid')
        if 21 <= avg <= 40:
            return _('Processing')
        if 41 <= avg <= 99:
            return _('Out for delivery')
        if avg == 100:
            return _('Delivered')


class OrderItem(models.Model):
    class Meta:
        ordering = ('datetime_added',)
        unique_together = ('order', 'product')

    TRACK_ORDER_CHOICES = (
        (20, 'Payed'),
        (40, 'Processing'),
        (80, 'Out for delivery'),
        (100, 'Delivered'),
    )
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name=_('product'))
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, related_name='items', null=True,
                              verbose_name=_('order'))
    quantity = models.PositiveIntegerField(default=0, null=True, blank=True, validators=[MinValueValidator(1)],
                                           verbose_name=_('quantity'))
    track_order = models.PositiveIntegerField(null=True, blank=True, choices=TRACK_ORDER_CHOICES)

    datetime_added = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime added'))

    # backup
    get_total_no_discount_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total no discount'))
    get_total_discount_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total discount'))
    get_total_profit_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total profit'))
    get_total_past = models.PositiveIntegerField(null=True, verbose_name=_('get cart total'))

    item_title = models.CharField(max_length=300, null=True, verbose_name=_('title'))
    item_cover = models.ImageField(upload_to='product_covers/', null=True, verbose_name=_('cover'))
    item_price = models.PositiveIntegerField(default=0, null=True, blank=True, verbose_name=_('price'))
    item_digital = models.BooleanField(default=False, null=True, blank=True, verbose_name=_('digital'))
    item_discount = models.BooleanField(default=False, verbose_name=_('discount'))
    item_discount_price = models.PositiveIntegerField(blank=True, null=True, verbose_name=_('discount price'))

    def __str__(self):
        try:
            order_item_str = str(f'order number: {self.order.pk}')
        except AttributeError:
            order_item_str = str(f'order item number: {self.pk} (the order item\'s is deleted)')
        return order_item_str

    def backup_product(self):
        self.item_title = self.product.title
        self.item_cover = self.product.cover
        self.item_price = self.product.price
        self.item_digital = self.product.digital
        self.item_discount = self.product.discount
        self.item_discount_price = self.product.discount_price

        self.get_total_no_discount_past = self.get_total_no_discount
        self.get_total_discount_past = self.get_total_discount
        self.get_total_profit_past = self.get_total_profit
        self.get_total_past = self.get_total
        self.save()

    def save_price(self):
        self.item_price = self.product.price
        self.save()

    @property
    def get_total_no_discount(self):
        return self.product.price * self.quantity

    @property
    def get_total_discount(self):
        if self.product.discount:
            return self.product.discount_price * self.quantity
        return 0

    @property
    def get_total_profit(self):
        if self.product.discount:
            return self.get_total_no_discount - self.get_total_discount
        return 0

    @property
    def get_total(self):
        return self.get_total_no_discount - self.get_total_profit


class ShippingAddress(models.Model):
    customer = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True,
                                 verbose_name=_('customer'))
    order = models.OneToOneField(Order, on_delete=models.SET_NULL, related_name='address', null=True, verbose_name=_('order'))
    state = models.CharField(max_length=200, null=True, verbose_name=_('state'))
    city = models.CharField(max_length=200, null=True, verbose_name=_('city'))
    address = models.TextField(null=True, verbose_name=_('address'))
    plate = models.PositiveIntegerField(null=True, verbose_name=_('plate'))
    datetime_added = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime added'))

    def __str__(self):
        return self.address

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Order, OrderItem, ShippingAddress


class OrderAdminForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

    def clean(self):
        clean_data = super().clean()

        if not clean_data.get('completed'):
            try:
                user = clean_data.get('customer')

                order = Order.objects.get(customer=user, completed=False)
                order_pk = order.pk
                self.add_error('customer', _(f'There is an incomplete order with pk {order_pk} for user {user}'))

            except Order.DoesNotExist:
                pass

        elif self.instance:
            try:
                self.instance.address
            except ShippingAddress.DoesNotExist:
                self.add_error(None, _('Complete order must have a shipping address'))

        return clean_data


class OrderItemAdminForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

    def clean(self):
        clean_data = super().clean()
        order = clean_data.get('order')

        if order.completed:
            self.add_error('order', _('This order is complete'))

        return clean_data


class OrderForm(forms.ModelForm):
    total = forms.IntegerField(min_value=0)

    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'phone', 'order_note')


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ('state', 'city', 'address', 'plate')

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib import messages
from django.views import generic
import json

from .models import Order, OrderItem
from products.models import Product
from .cart import Cart
from . import utils


def update_item(request):
    try:
        data = json.loads(request.body)
    except json.JSONDecodeError:
        messages.warning(request, _('Oops! Something went wrong with your request. Please try again.'
                                    ' If the issue persists, contact our support team for assistance.'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    quantity = data.get('quantity')
    try:
        quantity = int(quantity)
    except ValueError:
        quantity = 1

    if quantity != 0:
        customer = request.user
        product_id = data['productId']
        action = data['action']

        if customer.is_authenticated:
            order, order_created = Order.objects.get_or_create(customer=customer, completed=False)
            if action == 'delete_cart':
                order.items.all().delete()
                messages.success(request, _('Cart deleted'))
                return JsonResponse('finish update view', safe=False)

            product = get_object_or_404(Product, pk=product_id, active=True)

            try:
                item = OrderItem.objects.get(order=order, product=product)
            except OrderItem.DoesNotExist:
                if quantity < 0:
                    return JsonResponse('finish update view', safe=False)
                item = OrderItem.objects.create(order=order, product=product)

            if item.product.active:
                if item.quantity * -1 > quantity or action == 'delete_item':
                    item.delete()
                    messages.success(request, _('Delete product'))
                    return JsonResponse('finish update view', safe=False)

                elif action == 'add' and quantity > 0:
                    item.quantity += quantity
                    messages.success(request, _('Add product'))
                elif action == 'remove':
                    if quantity < 0:
                        quantity *= -1
                    item.quantity -= quantity
                    messages.success(request, _('Remove product'))

                item.save()

                if item.quantity <= 0:
                    item.delete()
                    messages.success(request, _('Delete product'))
        else:
            cart = Cart(request)
            if action == 'delete_cart':
                cart.clear_cart()
                messages.success(request, _('Cart deleted'))
            else:
                cart.update_quantity(product_id, action, quantity)

        return JsonResponse('finish update view', safe=False)

    else:
        messages.warning(request, _('Please enter a correct number!'))

    return JsonResponse('finish 0', safe=False)


def cart_view(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, completed=False)
        items = order.act_items().order_by('-datetime_added')
        order.del_in_act_items()
    else:
        cart = Cart(request)
        order = cart
        items = cart

    context = {
        'order': order,
        'items': items,
    }

    return render(request, 'cart/cart.html', context)


def checkout_view(request):
    # user with account
    if request.user.is_authenticated:
        checkout_login = utils.check_out_user_login(request)
        try:
            form_order, form_shipping, order, items = checkout_login
        except ValueError:
            return checkout_login

    # user without account
    else:
        order = cart = Cart(request)
        items = None

        checkout_anonymous = utils.check_out_user_anonymous(request, cart)
        try:
            form_order, form_shipping = checkout_anonymous
        except ValueError:
            return checkout_anonymous

    context = {
        'order': order,
        'items': items,
        'form_order': form_order,
        'form_shipping': form_shipping,
    }

    return render(request, 'cart/checkout.html', context)


class OrderReportAnonymous(generic.ListView):
    context_object_name = 'orders_completed'
    template_name = 'cart/order_anonymous.html'

    def get_queryset(self):
        try:
            orders_pk_list = self.request.session.get('orders_pk_list')
            orders = Order.objects.filter(id__in=orders_pk_list, completed=True)
            return orders
        except TypeError:
            orders_pk_list = []
            return orders_pk_list

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return reverse('accounts:profile')

        return super().dispatch(request, *args, **kwargs)


class OrderDetailView(generic.DetailView):
    template_name = 'cart/order_detail.html'
    context_object_name = 'order_finished'

    def get_object(self, queryset=None):
        order_pk = self.kwargs.get('pk')
        if self.request.user.is_authenticated:
            order = get_object_or_404(Order, pk=order_pk, customer=self.request.user, completed=True)

        else:
            order = None

        return order

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.info(request, _('for see order detail please login with email you ordered.'))
            return redirect('account_login')

        return super().dispatch(request, *args, **kwargs)

cart/templates/cart/cart.html
{% extends '_base.html' %}

{% load i18n %}
{% load trans_fa %}

{% block title %}{% trans 'Cart' %}{% endblock title %}

{% block content %}

    <!-- Breadcrumb area Start -->
    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                        {% if user.is_authenticated %}
                            <h1 class="page-title">{% trans 'Cart' %}</h1>
                        {% else %}
                            {% url 'cart:report_order_anony' as report_url %}
                            {% blocktrans %}
                            <h1 style="font-size: 2em;">If you want to see your orders without registration,
                                <a href="{{ report_url }}">click on the link</a></h1>
                            {% endblocktrans %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb area End -->

    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">
                        <form class="cart-form" action="#">
                            <div class="row no-gutters">
                                <div class="col-12">
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>{% trans 'Product Photo' %}</th>
                                                <th class="text-left">{% trans 'Product Name' %}</th>
                                                <th>{% trans 'Price' %}</th>
                                                <th>{% trans 'Discount Price' %}</th>
                                                <th>{% trans 'Quantity' %}</th>
                                                <th>{% trans 'Total' %}</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in items %}
                                                <tr>
                                                    <td class="product-remove text-left"><button class="astext update-cart" style="color: red;" data-action="delete_item" data-product="{{ item.product.pk }}" href=""><i
                                                            class="flaticon flaticon-cross"></i></button></td>
                                                    <td class="product-thumbnail text-left ">
                                                        <img class="img-thumbnail" src="{{ item.product.cover.url }}"
                                                             alt="Product Thumnail">
                                                    </td>
                                                    <td class="product-name wide-column">
                                                        <h3>
                                                            <a href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                        <span class="product-price-wrapper">
                                                                <span class="money">{% trans '$' %} {{ item.product.price|num_fa }}</span>
                                                        </span>
                                                    </td>
                                                    <td class="product-price">
                                                        <span class="product-price-wrapper">
                                                            {% if item.product.discount %}
                                                                <span class="money">{% trans '$' %} {{ item.product.discount_price|num_fa }}</span>
                                                            {% endif %}
                                                        </span>
                                                    </td>
                                                    <td class="product-quantity">
                                                        <div class="">
                                                            <input type="number" class="quantity-input update-cart"
                                                                   name="qty"
                                                                   id="qty-1" value="{{ item.quantity }}" min="1" >
                                                            <div class="dec qtybutton update-cart"
                                                                 data-product="{{ item.product.pk }}"
                                                                 data-action="remove">-
                                                            </div>
                                                            <div class="inc qtybutton update-cart"
                                                                 data-product="{{ item.product.pk }}" data-action="add">
                                                                +
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{% trans '$' %} {{ item.get_total|num_fa }}</span>
                                                            </span>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </form>
                        {% if items %}
                            <div class="row no-gutters border-top pt--20 mt--20">
                                <div class="col-sm-6 text-sm-right">
                                    <button class="astext cart-form__btn update-cart" data-product="" data-action="delete_cart">{% trans 'Empty the shopping cart' %}</button>
                                </div>
                            </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="cart-collaterals">
                                    <div class="cart-totals">
                                        <div class="cart-calculator">
                                            <div class="cart-calculator__item">
                                                <div class="cart-calculator__item--head">
                                                    <span>{% trans 'total' %}</span>
                                                </div>
                                                <div class="cart-calculator__item--value">
                                                    <span>{% trans '$' %} {{ order.get_cart_total_no_discount|num_fa }}</span>
                                                </div>
                                            </div>
                                            <div class="cart-calculator__item">
                                                <div class="cart-calculator__item--head">
                                                    <span>{% trans 'Profit' %}</span>
                                                </div>
                                                <div class="cart-calculator__item--value">
                                                    <span>{% trans '$' %} {{ order.get_cart_total_profit|num_fa }}</span>
                                                </div>
                                            </div>
                                            <div class="cart-calculator__item order-total">
                                                <div class="cart-calculator__item--head">
                                                    <span>{% trans 'sum total' %}</span>
                                                </div>
                                                <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{% trans '$' %} {{ order.get_cart_total|num_fa }}</span>
                                                </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="{% url 'cart:checkout' %}"
                                       class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                        {% trans 'Checkout' %}
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->

{% endblock content %}