accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('username/set/', views.set_username_view, name='set_username'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart_page'),
    path('update-item/', views.update_item, name='update_item'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('report-order/', views.OrderReportAnonymous.as_view(), name='report_order_anony'),
    path('order-detail/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/password/change/', views.CustomPasswordChangeView.as_view(), name='custom_account_change_password'),
    path('accounts/password/set/', views.CustomPasswordSetView.as_view(), name='custom_account_set_password'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('general.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, re_path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductsListView.as_view(), name='products_list'),
    path('search/', views.SearchView.as_view(), name='search_page'),
    path('favorite/', views.favorite_view, name='favorite'),
    re_path(r'category/(?P<slug>[-\w]+)/', views.CategoryView.as_view(), name='category_page'),
    re_path(r'(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name='product_detail'),
]

accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth import get_user_model


class SetUsername(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='set_username')
    first_time = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile', verbose_name=_('User'))
    location = models.TextField(blank=True, verbose_name=_('Location'))
    first_name = models.CharField(max_length=200, blank=True, verbose_name=_('First name'))
    last_name = models.CharField(max_length=200, blank=True, verbose_name=_('Last name'))
    phone = PhoneNumberField(unique=True, blank=True, null=True, region='', verbose_name=_('phone'))
    picture = models.ImageField(upload_to='accounts_pictures/', blank=True, null=True, verbose_name=_('picture'))

    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime created'))
    datetime_modified = models.DateTimeField(auto_now_add=True, verbose_name=_('datetime modified'))

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms

from phonenumber_field.widgets import PhoneNumberPrefixWidget

from .models import Profile


class SetUsernameForm(forms.Form):
    username = forms.CharField(max_length=100)


class ProfileForm(forms.ModelForm):
    class Meta:
        REGION_CHOICE = (
            ('IR', '+98'),
            ('US', '+1'),
        )
        
        model = Profile
        fields = ('first_name', 'last_name', 'picture', 'location', 'phone')

        widgets = {
            'picture': forms.FileInput,
            'phone': PhoneNumberPrefixWidget(country_choices=REGION_CHOICE),
        }

accounts/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.utils.translation import gettext_lazy as _
from django.db.utils import IntegrityError
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db import transaction

from allauth.account.views import PasswordChangeView, PasswordSetView

from cart.models import Order
from .forms import SetUsernameForm, ProfileForm
from .models import Profile, SetUsername
from products.models import Product


class CustomPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('general:home')


class CustomPasswordSetView(PasswordSetView):
    success_url = reverse_lazy('general:home')


@login_required
def set_username_view(request):
    user_obj = request.user
    form = SetUsernameForm(request.POST or None)

    if form.is_valid():
        set_username, create = SetUsername.objects.get_or_create(user=user_obj)
        if set_username.first_time:
            try:
                with transaction.atomic():
                    user_obj.username = form.cleaned_data['username']
                    user_obj.save()
            except IntegrityError:
                form.add_error('username', 'This username exist!')
                context = {'form': form}
                return render(request, 'accounts/set_username.html', context)

            set_username.first_time = False
            set_username.save()
            return redirect('general:home')

        else:
            form.add_error('username', _('You changed your username'))

    context = {
        'form': form
    }

    return render(request, 'accounts/set_username.html', context)


class ProfileView(LoginRequiredMixin, generic.UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        profile_user, create = Profile.objects.get_or_create(user=self.request.user)
        return profile_user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products_list = Product.objects.filter(favorite=self.request.user.pk, active=True).order_by(
            '-datetime_like__datetime_like')
        for product in products_list:
            product.time_like = product.get_time_like(self.request.user)
        context['products'] = products_list
        context['orders_completed'] = Order.objects.filter(customer=self.request.user, completed=True).order_by(
            '-datetime_ordered')

        return context

accounts/templates/accounts/profile.html
{% extends '_base.html' %}

{% load i18n %}
{% load crispy_forms_filters %}
{% load static %}
{% load trans_fa %}

{% block title %}{% trans 'Profile' %}{% endblock title %}

{% block content %}
    <!-- Breadcrumb area Start -->
    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                        <h1 class="page-title">{% trans 'User profile' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb area End -->

    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="user-dashboard-tab flex-column flex-md-row">
                            <div class="user-dashboard-tab__head nav flex-md-column" role="tablist"
                                 aria-orientation="vertical">
                                <a class="nav-link active" data-toggle="pill" role="tab" href="#dashboard"
                                   aria-controls="dashboard" aria-selected="true">{% trans 'Counter' %}</a>
                                <a class="nav-link" data-toggle="pill" role="tab" href="#orders" aria-controls="orders"
                                   aria-selected="true">{% trans 'Order history' %}</a>
                                <a class="nav-link" data-toggle="pill" role="tab" href="#addresses"
                                   aria-controls="addresses" aria-selected="true">{% trans 'Favorites' %}</a>
                                <a class="nav-link" data-toggle="pill" role="tab" href="#accountdetails"
                                   aria-controls="accountdetails" aria-selected="true">{% trans 'Profile detail' %}</a>
                                {% if user.has_usable_password %}
                                    <a class="nav-link" href="{% url 'account_change_password' %}"
                                    >{% trans 'Change password' %}</a>
                                {% else %}
                                    <a class="nav-link" href="{% url 'account_set_password' %}"
                                    >{% trans 'Set password' %}</a>
                                {% endif %}
                                <a class="nav-link" href="{% url 'account_logout' %}">{% trans 'Log out' %}</a>
                            </div>
                            <div class="user-dashboard-tab__content tab-content p-4">
                                <div class="tab-pane fade show active" id="dashboard">
                                </div>
                                <div class="tab-pane fade" id="orders">
                                    {% if orders_completed|length == 0 %}
                                        <p>
                                            <i class=""></i>{% trans 'No order has been registered yet!' %}
                                        </p>
                                        <a href="{% url 'products:products_list' %}">{% trans 'Go to the store' %}</a>
                                    {% else %}
                                        <div class="table-content table-responsive">
                                            <table class="table text-center">
                                                <thead>
                                                <tr>
                                                    <th>{% trans 'Order Number' %}</th>
                                                    <th>{% trans 'Date' %}</th>
                                                    <th>{% trans 'Status' %}</th>
                                                    <th>{% trans 'Total' %}</th>
                                                    <th>{% trans 'Operation' %}</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for order in orders_completed %}
                                                    <tr>
                                                        <td>{{ forloop.counter }}</td>
                                                        <td class="wide-column">{{ order.format_time_ordered }}</td>
                                                        <td>{{ order.avg_track_items }}</td>
                                                        <td class="wide-column">
                                                            {% trans '$' %}{{ order.get_cart_total_past|num_fa }} {% trans 'for' %} {{ order.get_cart_items_past|num_fa }} {% trans 'item' %}
                                                        </td>
                                                        <td><a href="{% url 'cart:order_detail' order.pk %}"
                                                               class="btn btn-small btn-bg-red btn-color-white btn-hover-2">{% trans 'Visit' %}</a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="tab-pane fade" id="addresses">
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                            <tr>
                                                <th>{% trans 'Number' %}</th>
                                                <th>{% trans 'Product Name' %}</th>
                                                <th>{% trans 'Product Photo' %}</th>
                                                <th>{% trans 'Date of interest' %}</th>
                                                <th>{% trans 'Operation' %}</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for product in products %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ product.title }}</td>
                                                    <td class="wide-column"><img class="img-thumbnail"
                                                                                 style="width: 100px; height: auto;"
                                                                                 src="{{ product.cover.url }}" alt="">
                                                    </td>
                                                    <td class="wide-column">{{ product.time_like }}</td>
                                                    <td><a href="{{ product.get_absolute_url }}"
                                                           class="btn btn-small btn-bg-red btn-color-white btn-hover-2">{% trans 'Visit' %}</a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="accountdetails">
                                    <p>{% trans 'Username:' %} <strong>{{ user }}</strong></p>
                                    {% if user.set_username.first_time %}
                                        <p>
                                            {% trans "You didn't set username. Click on" %}
                                            <a class="forgot-pass" href="{% url 'accounts:set_username' %}"><strong>{% trans 'set username' %}</strong></a>
                                            {% trans 'to redirect. But pay attention You can set your username for one time!' %}
                                        </p>
                                    {% endif %}
                                    <form action="" class="form form--account" method="post"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form__group">
                                                    <input type="submit" value="{% trans 'Save changes' %}"
                                                           class="btn btn-style-1 btn-submit">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->


{% endblock content %}

accounts/templates/accounts/set_username.html
{% extends '_base.html' %}

{% load i18n %}
{% load crispy_forms_filters %}

{% block title %}{% trans 'Set username' %}{% endblock title %}

{% block content %}

    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                        <h1 class="page-title">{% trans 'You can set your username one time!' %}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-content-wrapper">
        <div class="page-content-inner pt--75 pb--80">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 mb-sm--50">
                        <div class="login-box">
                            <form action="{% url 'accounts:set_username' %}" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <div class="d-flex align-items-center mt--20">
                                    <div class="form__group">
                                        <input type="submit" value="{% trans "Set" %}" class="btn-submit">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}